version: "3.9"
services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: realworld
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
 
volumes:
  pg-data: